### ISSUE TITLE
[BUG]: 用户删除自己评论时，未通过权限检查

### ISSUE THREAD

**Issue by systemime** [xxiaocheng/flask_douban_moive_web#3]
在如下代码部分，删除评论时对用户的检查，
if条件是不是应该是`this_user == this_rating.user`, 而不是`this_rating == this_rating`
```python
# app/v2/rating.py 63

class Rating(Resource):
    ......
    @auth.login_required
    def delete(self, rating_hash_id):
        ......
        this_user = g.current_user
        if this_rating == this_rating.user or this_user.check_permission(
            "HANDLE_REPORT"
        ):
            ......
```

当前master分支代码，用户无法删除自己评论

**Comment by xxiaocheng** [comment]
> 在如下代码部分，删除评论时对用户的检查，
> if条件是不是应该是`this_user == this_rating.user`, 而不是`this_rating == this_rating`
> 
> ```python
> # app/v2/rating.py 63
> 
> class Rating(Resource):
>     ......
>     @auth.login_required
>     def delete(self, rating_hash_id):
>         ......
>         this_user = g.current_user
>         if this_rating == this_rating.user or this_user.check_permission(
>             "HANDLE_REPORT"
>         ):
>             ......
> ```
> 
> 当前master分支代码，用户无法删除自己评论

是的，这个是写错了
